version: '3.2'
services:
  trpl-pdf-compile:
    image: ghcr.io/rust-lang-ja/book-ja-pdf:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - ghcr.io/rust-lang-ja/book-ja-pdf:latest
    volumes:
      - .:/workdir
