name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Docker image
      run: docker-compose pull
      continue-on-error: true

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: ghcr.io/rust-lang-ja/book-ja-pdf:latest

    - name: PDF build
      run: docker-compose up --abort-on-container-exit

    - name: Push PDF file
      uses: actions/upload-artifact@v2
      with:
        name: trpl book japanese
        path: book.pdf
      if: ${{ github.ref == 'refs/heads/master' }}

  release:
    name: Publish artifact to gh-pages
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: trpl book japanese
          path: ./build/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          target-folder: ./
          clean: true
