name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Docker image
      run: docker-compose pull
      continue-on-error: true

    - name: Build Docker image
      run: docker-compose build

    - name: PDF build
      run: docker-compose up --abort-on-container-exit
      
    - name: Push Docker image
      run: docker-compose push
      if: ${{ github.ref == 'refs/heads/master' }}

    - name: Push PDF file
      uses: actions/upload-artifact@v2
      with:
        name: trpl book japanese
        path: book.pdf
      if: ${{ github.ref == 'refs/heads/master' }}

  release:
    name: Publish artifact to gh-pages
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: trpl book japanese
          path: ./build/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          target-folder: ./
          clean: true
